[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal ARKane crates
ark-core = { path = "../ark-core" }
ark-grpc = { path = "../ark-grpc" }

# Web framework and HTTP
actix-web = "4"
esplora-client = { version = "0.10", features = ["async-https"] }

# Bitcoin-related
bitcoin = { version = "0.32" }

# Asynchronous runtime and utilities
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures = "0.3"

# Error handling
anyhow = "1"

# Serialization/Deserialization
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
toml = "0.7"
jiff = "0.2.1"

# CLI arguments
clap = { version = "4", features = ["derive"] }

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "ansi", "env-filter", "time", "tracing-log", "json"] }

# Utilities
rand = "0.8"
uuid = { version = "1.4", features = ["v4", "serde"] }
regex = "1.10.2"
hex = "0.4.3"
